### ISSUE TITLE
World model placed via editor doesn't play animation

### ISSUE THREAD

**Issue by Descen** [wootguy/weapon_custom#9]
As the title says the w_model placed via the level editor wont play in game. In my case I edited the world model to have an arcade style floating, rotating idle animation. But in game the model being static, supposedly stuck on the first frame. But when you drop the weapon, the dropped model plays the animation without issues.

**Comment by wootguy** [comment]
updated [WeaponCustomBase.as](https://raw.githubusercontent.com/wootguy/weapon_custom/refs/heads/master/WeaponCustomBase.as) for this
